### ISSUE TITLE
css stops working if DEBUG = False

### ISSUE THREAD

**Issue by grantal** [ifjorissen/vrfy#108]
if you turn off debug in settings.py the site ends up looking like this:
![debug](https://cloud.githubusercontent.com/assets/7049313/9235921/9b8f4666-40f6-11e5-87cc-632bcd4aa136.png)

**Comment by ifjorissen** [comment]
@AlexV348 if memory serves, this is totally fine (?). When we're in production we'll be able to configure our server (I think i did this with Nginx in the past) to serve static media files from a different location.
