### ISSUE TITLE
presentation of plaintext descriptions

### ISSUE THREAD

**Issue by jimfix** [ifjorissen/vrfy#132]
This is not of the highest priority, but I would use the "description" field more if it was presented in a fixed width font.  That way I can describe code, and suggest expected Terminal output.  Here is an
example description of a problem from Exercise 3 of this Lab 04 page:

http://people.reed.edu/~jimfix/math121/past/4102/labs/lab04.html

```
house

Write a program house.py that defines a function 'house',
when given two positive integers, outputs the picture of
a house whose building is of that width and height, and
whose roof is of that width.

  def house(width,height): ...

For example, a Python script that called 'house(4,5)'
would produce the following 'print' lines of output:

   *
  * *
 * * *
* * * *
*     *
*     *
*     *
* * * *
```

**Comment by jimfix** [comment]
Instead I will probably have a separate web page of the assignment, and only have CSHW descriptions be terse.

**Comment by Gastove** [comment]
It wouldn't be difficult to make the `description` field markdown-able, which would allow for very easy integration of fixed-width sections.

**Comment by Gastove** [comment]
Oh wait this totally works, I believe -- we can re-open if it doesn't.
