### ISSUE TITLE
link to submit problem

### ISSUE THREAD

**Issue by jimfix** [ifjorissen/vrfy#133]
I think it's cool that I can have a HTML link (on a course page) for a student to click on that takes them to the CSHW submission summary page for a problem set.  

It might also be useful for some instructors if they can have an HTML link (on their course page) for a student to click on that takes them to a version of that page where a specific problem is "uncollapsed for submission", and all the other problems on that page are "collapsed".  Basically, I'd want my course web page for a problem set to have a "submit your answer to this problem" link next to an individual problem.

This may not be possible under the current framework, but I thought I'd vote for it.

**Comment by Gastove** [comment]
Closing this; reopen as needed.
