### ISSUE TITLE
during system updates, proxy error message should be thoughtful

### ISSUE THREAD

**Issue by jimfix** [ifjorissen/vrfy#136]
Tried to go to cs.reed.edu/admin while Isabella was updating things. I got this:
![proxyerror](https://cloud.githubusercontent.com/assets/8050202/9568836/7ef88e18-4f0b-11e5-84f5-c0197e2f227c.jpg)

I'd imagine a student would see something similar.  We oughta be able to apply updates to the system and let students know that the system is temporarily down, "try again later". "try again in a few minutes", whatever that message should be.

**Comment by ifjorissen** [comment]
moved to https://github.com/reed-college/vrfy/issues/19
