### ISSUE TITLE
long file paths issue

### ISSUE THREAD

**Issue by jimfix** [ifjorissen/vrfy#158]
In order to distinguish problems on problem sets (to avoid collisions or confusion), we've been naming problem sets and problems with longer names (e.g. "hw1 ex3a digits: hundred_digits (fix)" on "hw1 digits zap buzz (fix)").  This seems to cause a problem when some students submit their code. There seems to be a "max_length" suggestion from the system that leads to a "SuspiciousFileOperation" yellow pane. The error message suggests that the file path for the submission's test may be too long.

**Comment by ifjorissen** [comment]
increased file name length to 1000 chars in a previous pr
