### ISSUE TITLE
FileNotFound Error when deleting some problems

### ISSUE THREAD

**Issue by ifjorissen** [ifjorissen/vrfy#161]

**Comment by Gastove** [comment]
Related to #167?

**Comment by ifjorissen** [comment]
Kind of, I'm not really sure what @AlexV348 was getting at there, maybe he can chime in?

**Comment by ifjorissen** [comment]
E.g: 

```
[Errno 2] No such file or directory: '/home/vrfy/vrfy/problem_assets/121/solutions/hw9-ll-delete-groce_files/test_delete.py'
```

Pretty sure this is an issue with the problem names and the problem file names. We're creating folders based on the problem name and that causes issues when problems are not uniquely named. We should probably modify this to include the problem id + problem name to avoid this issue. Currently, if two problems with the same name are created and have the same assets, if one of the problems gets deleted both of the files get deleted. The FileNotFound error is likely a result of accessing the duplicate problem and attempting to get its associated files only to find out that they're no longer there...
