### ISSUE TITLE
Backups! 

### ISSUE THREAD

**Issue by Gastove** [ifjorissen/vrfy#170]
Backups are good news. TIS is currently capturing VM snapshots every 24 hours, which is a start. Even better is a more explicit, internal system, storing mission critical information someplace useful.

The most crucial thing to capture is student assignment uploads -- and, ideally, every version of each upload -- followed by a snapshot of Postgres and media/assets. The filesystem should be a sufficiently secure place to put these backups, where they can then be handled properly by rsync/rsnapshot. The current intention is to back up every two hours.

Known things to figure out:
- [x] Where is Django putting files as it uploads them, and how does it handle versioning?

**Comment by Gastove** [comment]
@ifjorissen and I knocked out a lot of this today. `vrfy` now writes tarballs of its static assets and the DB in to a known folder; next step is to check with TIS about backing up those files somewhere not on the same server.

**Comment by Gastove** [comment]
Last step: do a restore, make sure it works correctly.

**Comment by ifjorissen** [comment]
@Gastove good to close?

**Comment by Gastove** [comment]
:+1:
