### ISSUE TITLE
Scrub Up the Codes

### ISSUE THREAD

**Issue by Gastove** [ifjorissen/vrfy#174]
`vrfy`'s code-base could use a tidying up. In particular:
- [ ] Much of the code lacks doc strings or descriptive comments
- [ ] Test coverage is a little thin (see #79)
- [ ] Analysis with `flake8` suggests many imports are unused (not always accurate, but worth cleaning up.
- [ ] A lot of code is commented out, but without descriptive comments indicating why. This code should either be documented or removed.

**Comment by grantal** [comment]
This issue was moved to reed-college/vrfy#10
