### ISSUE TITLE
Fixturez

### ISSUE THREAD

**Issue by Gastove** [ifjorissen/vrfy#176]
Right now, the only fixture in `vrfy` is for the `course` app, and it'll wreck yer DB (expect a lot of `django.db.utils.IntegrityError: Problem installing fixture '/Users/gastove/Code/reed_sds/vrfy/course/fixtures/initial_data.json': Could not load contenttypes.ContentType(pk=7): duplicate key value violates unique constraint "django_content_type_app_label_122a72a237015468_uniq"
DETAIL:  Key (app_label, model)=(catalog, course) already exists.`). Let's... make that not be like that.

**Comment by grantal** [comment]
This issue was moved to reed-college/vrfy#11
