### ISSUE TITLE
Plagiarism Checks

### ISSUE THREAD

**Issue by grantal** [ifjorissen/vrfy#193]
- Check if student files look the same
  - also check for things like variable name changes
- Also check against solutions found on google

**Comment by Gastove** [comment]
Curious: who/what is motivating this? The notion of plagiarism is well understood for, say, essays -- but for code, I think this might get problematic in a hurry.

**Comment by grantal** [comment]
Adam said on a recent assignment that some student people had similar solutions to a problem and one even commented that he copied the solution from the internet. He also said this is more of a long term goal since the semester is almost over anyways.

**Comment by jimfix** [comment]
I think code similarity checks have become a common thing in this kind of software project. There may also be existing packages/systems.  For example:

https://theory.stanford.edu/~aiken/moss/

-j

**Comment by grantal** [comment]
This issue was moved to reed-college/vrfy#3
