### ISSUE TITLE
backup deletion on cshw

### ISSUE THREAD

**Issue by ifjorissen** [ifjorissen/vrfy#204]
vrfy's database & media gets backed up every two hours. That takes up space. 

@Gastove and I wrote a cron job to do all that backing up stuff. But, vrfy needs another job to clean up after that first job's mess. 

write a script to remove old backups after an appropriate amount of time. (a week? month?)
the backups are stored in `vrfy/vrfy_backups/` on cshw.reed.edu

**Comment by grantal** [comment]
This issue was moved to reed-college/vrfy#1

**Comment by ifjorissen** [comment]
closing b/c this has been moved to reed-college's fork.
