### ISSUE TITLE
Problem Results should probably have an attempt associated with them

### ISSUE THREAD

**Issue by ifjorissen** [ifjorissen/vrfy#76]
problem results are created regardless of whether or not the problem is autograded. Since the student solution only keeps track of the most recent attempt number, getting the attempt number of a ProblemResult is currently done (though not yet in master, as i'm working on this locally) by accessing the attempts from the json_log. However, if the json_log is not generated because the problem is not autograded, there isn't a way to figure out which attempt this is.

Proposed solution: add an attempt number to the ProblemResult Model

thoughts? @AlexV348

**Comment by grantal** [comment]
I think thats a good solution
