### ISSUE TITLE
Fix old tests and make new tests

### ISSUE THREAD

**Issue by grantal** [ifjorissen/vrfy#79]

**Comment by Gastove** [comment]
Test coverage is slightly lacking, making it difficult for collaborators to make sure they aren't affecting core functionality. Let's get some basic Unit Testing in place -- and _then_: Integration tests. Oh my.

**Comment by Gastove** [comment]
Current testing seems to assume you have a running Tango instance. This is... problematic. Strong suggestion: replace with [mock](https://mock.readthedocs.org/en/latest/)
