### ISSUE TITLE
add more logic to re-attempt

### ISSUE THREAD

**Issue by ifjorissen** [ifjorissen/vrfy#90]
if not all problems are attempted, should read: attempt more problems
if all problems have been attempted, it should read reattempt

**Comment by stellarluminary** [comment]
This sounds like an if/else setup. Do you mean that the button on the homepage for the Due Soon problem sets?

**Comment by ifjorissen** [comment]
@jlhwang this happens in a couple places, and is part of the bug I'm fixing now, where student solutions are being created before submissions are actually handled so it requires a non-trivial amount of logic to determine lateness, whether or not it has been attempted / needs to be reattempted etc. It _should_ be an if/else setup insofaras the answer is either yes or no in most cases (lateness, attempts, etc). However, that's not quite how it works right now
